spring.application.name=auth-demo

server.port=8080


spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=postgres
spring.datasource.password=251198@Ht
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


jwt.secret=9a2f8c4e1b7d3f6a8e0c2b5d7e9f1a4b6c8d0e3f5a7b9c1d3e5f7a9b2c4d6e8f
jwt.expiration=86400000